# Generated by Django 4.0.5 on 2022-07-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_cursos_options_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComCont',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(verbose_name='Usuario')),
                ('mensaje', models.TextField(verbose_name='Comentario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
            ],
            options={
                'verbose_name': 'Comentarios de Contactos',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['created'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
    ]
